version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    docker:
      - image: cimg/node:18.19.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build application
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .next
            - node_modules
            - package.json
            - package-lock.json

  deploy:
    docker:
      - image: cimg/node:18.19.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install Vercel CLI
          command: npm install -g vercel@latest
      - run:
          name: Deploy to Vercel
          command: |
            vercel --prod --token $VERCEL_TOKEN --confirm
          environment:
            VERCEL_TOKEN: $VERCEL_TOKEN
            VERCEL_ORG_ID: $VERCEL_ORG_ID
            VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main 